# Generated by Django 4.2.16 on 2026-06-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='paintings/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='auth_api.appuser')),
            ],
            options={
                'db_table': 'paintings',
                'ordering': ['-created_at'],
            },
        ),
    ]
